//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public int TransactionDetailsId { get; set; }
        public int TransactionCategoryId { get; set; }
        public string TransactionDetailsName { get; set; }
        public int TransactionTypeId { get; set; }
        public int ExpenseTypeId { get; set; }
        public int ExpenseAmountTypeId { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ExpenseAmountType ExpenseAmountType { get; set; }
        public virtual ExpenseType ExpenseType { get; set; }
        public virtual TransactionCategory TransactionCategory { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
