//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFM.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankStatement
    {
        public int BankStatementId { get; set; }
        public int BankAccountTypeId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public System.DateTime PostingDate { get; set; }
        public string TransactionDescription { get; set; }
        public Nullable<int> TransacionNumber { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
    
        public virtual BankAccountType BankAccountType { get; set; }
    }
}
