//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFM.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> ItemCategoryId { get; set; }
        public Nullable<int> ItemSubCategoryId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> QuantityId { get; set; }
    
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual ItemSubCategory ItemSubCategory { get; set; }
        public virtual QuantityType QuantityType { get; set; }
        public virtual Store Store { get; set; }
    }
}
