//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFM.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreInventory
    {
        public int StoreInventoryId { get; set; }
        public int StoreId { get; set; }
        public Nullable<int> InventoryId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal MRP { get; set; }
        public decimal Tax { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual PurchaseLocation PurchaseLocation { get; set; }
        public virtual Store Store { get; set; }
    }
}
